window.JSTAGE_PAPERS = [
  {
    "title": "アルカリ活性化されたアルミノケイ酸塩によるセシウム溶液の不溶化処理",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/4/9_173/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "数学"
  },
  {
    "title": "福島第一原発事故とチェルノブイリ原発事故後の農耕地における放射性セシウムの挙動に対する耕うんの影響比較",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/3/9_117/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "物理学"
  },
  {
    "title": "飯舘村長泥地区の農地造成に利用が計画されている土壌における作物の生育および放射性セシウムの移行性の解析",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/3/9_131/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "化学"
  },
  {
    "title": "除去土壌等の保管が終了した仮置場の保管場所跡地における効率的な空間線量率の測定",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/3/9_145/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "地球科学・天文学"
  },
  {
    "title": "粘性土を多く含む除去土壌減容化のための分級処理の改善と課題",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/2/9_59/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "生物学・生命科学・基礎医学"
  },
  {
    "title": "賦活化木炭のCs吸着能とその焼却時の減容化率及びCs回収率について",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/2/9_69/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "農学・食品科学"
  },
  {
    "title": "福島第一原発事故で発生した高放射線土「黒い土」とその高い放射線の原因 －スメクタイト内の放射性セシウム濃集の詳細－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/2/9_77/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般医学・社会医学・看護学"
  },
  {
    "title": "除去土壌分級処理のための粘性土の濃縮脱水法",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/1/9_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "臨床医学"
  },
  {
    "title": "大気圧非平衡プラズマ賦活処理が活性炭及び竹炭のCs吸着能に及ぼす影響",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/9/1/9_17/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "歯学"
  },
  {
    "title": "水熱法での放射性セシウム鉱物化における共存アルカリ金属イオンの影響（1）：懸濁溶液からのポルサイトの合成",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/4/8_181/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "薬学"
  },
  {
    "title": "土壌との混合による飛灰からのCs溶出率制御の可能性",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/4/8_197/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般工学・総合工学"
  },
  {
    "title": "福島第一原子力発電所事故による放射性物質汚染の実態 ―2019年、福島県二本松市の汚染の現状と黒い土―",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/4/8_207/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "ナノ・材料科学"
  },
  {
    "title": "除染の完了から2年半後における除染特別地域内の市町村の除染に関する現状認識と課題認識",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/3/8_111/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "建築学・土木工学"
  },
  {
    "title": "廃棄物焼却におけるストロンチウムの挙動と溶出特性",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/3/8_133/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "機械工学"
  },
  {
    "title": "福島第一原発事故由来の放射性セシウムによる 汚染物の処理・処分方法の総合的比較（第2報） －焼却残渣に対する減容化プロセス5CASEの比較－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/3/8_147/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "電気電子工学"
  },
  {
    "title": "Ion Chromatographic Decontamination of 137Cs-enriched Fly Ash Using Poly (vinyl alcohol)-bound Copper Ferrocyanide as Cs Adsorbent",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/2/8_55/_article/-char/ja",
    "journal": "Journal of the Society for Remediation of Radioactive Contamination in the Environment",
    "category": "情報科学"
  },
  {
    "title": "除染の完了から1 年半後における市町村除染地域内の市町村の除染に関する現状認識と課題認識",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/2/8_67/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "環境学"
  },
  {
    "title": "Metakaolin-based Geopolymer for Immobilizing Concentrated Cs Generated by Volume Reduction of 137Cs-contaminated Waste",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/1/8_3/_article/-char/ja",
    "journal": "Journal of the Society for Remediation of Radioactive Contamination in the Environment",
    "category": "学際科学"
  },
  {
    "title": "腐植質を含む粘性土の湿式解泥工学的粉体特性と陽イオン収着特性",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/8/1/8_17/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "哲学・宗教"
  },
  {
    "title": "飯舘村蕨平における放射性物質の分離による焼却灰及び汚染土壌の資材化に関する研究",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/4/7_227/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "文学・言語学・芸術学"
  },
  {
    "title": "福島第一原子力発電所事故由来の放射性セシウムによる汚染物の処理・処分方法の総合的比較（第1報） 焼却残渣の熱処理・灰洗浄を含む減容化プロセスの定量的評価方法の開発",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/4/7_241/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "人類学・史学・地理学"
  },
  {
    "title": "イノシシ体内に含まれる放射性セシウム量推定方法の検討 - 体組織別調査と焼却残渣調査の実施",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/3/7_165/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "法学・政治学"
  },
  {
    "title": "森林バイオマスの減量・低濃度化のための湿式酸化法操作条件の検討",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/3/7_175/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "経済学・経営学"
  },
  {
    "title": "放射能汚染した廃棄物処分におけるコンクリートのアルカリ骨材反応の抑制の意義",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/2/7_77/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "社会学"
  },
  {
    "title": "除染の完了後における市町村除染地域内の市町村の除染に関する現状認識と課題認識 － 2018 年の市町村アンケート調査の結果に基づいて－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/2/7_87/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "心理学・教育学"
  },
  {
    "title": "福島において採取された放射能汚染土壌の物理的化学的特性",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/2/7_115/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "数学"
  },
  {
    "title": "高炉スラグ微粉末を利用した磁選による放射性セシウム汚染土壌の乾式分級",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/1/7_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "物理学"
  },
  {
    "title": "除染の完了後における除染特別地域内の市町村の除染に関する現状認識と課題認識 －2018年の市町村アンケート調査の結果に基づいて－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/7/1/7_13/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "化学"
  },
  {
    "title": "「除染の完了」後における市町村主体の除染に関する課題",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/4/6_231/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "地球科学・天文学"
  },
  {
    "title": "福島の安全・安心を確実なものにするために！",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/4/6_265/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "生物学・生命科学・基礎医学"
  },
  {
    "title": "モンテカルロ放射線輸送コード(PHITS)を用いた森林内空間線量評価ツールの開発",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/3/6_145/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "農学・食品科学"
  },
  {
    "title": "汚染土壌の減容化に向けた放射性セシウムイオン除去: ミニフィールド装置によるオンサイト実験",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/3/6_153/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般医学・社会医学・看護学"
  },
  {
    "title": "「除染の完了」後における除染特別地域内の市町村の除染に関する評価",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/3/6_163/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "臨床医学"
  },
  {
    "title": "焼成技術を活用した汚染土壌の再利用に関する研究",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/2/6_63/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "歯学"
  },
  {
    "title": "Super Volume Reduction of 137Cs-contaminated Solid Waste by Ion Chromatographic Elimination of Cs from 137Cs-enriched Dust Generated by Pyroprocessing Decontamination",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/2/6_73/_article/-char/ja",
    "journal": "Journal of the Society for Remediation of Radioactive Contamination in the Environment",
    "category": "薬学"
  },
  {
    "title": "空間線量率指向性モニタリング装置の開発と測定評価",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/2/6_81/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般工学・総合工学"
  },
  {
    "title": "野焼きを想定した雑草の燃焼による放射性セシウムの動態",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/2/6_91/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "ナノ・材料科学"
  },
  {
    "title": "加熱化学処理法による焼却主灰からの放射性セシウム除去および除去メカニズムの推定",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/1/6_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "建築学・土木工学"
  },
  {
    "title": "溜め池底質用放射性セシウム鉛直分布測定パイプと多地点同時測定システムの開発",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/1/6_17/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "機械工学"
  },
  {
    "title": "稲わらの放射性セシウム濃度測定における測定誤差に関する検討",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/6/1/6_25/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "電気電子工学"
  },
  {
    "title": "除去土壌フレコン中の放射性Cs濃度の推定",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/4/5_255/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "情報科学"
  },
  {
    "title": "福島県における市町村主体の除染の実態と課題 －2012年から2016年までの市町村アンケート調査の結果に基づいて－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/4/5_267/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "環境学"
  },
  {
    "title": "Estimation of the Time of Cesium Leaking by Moisture Absorption of Radiologically Contaminated Municipal Solid Waste Incinerator Fly Ash",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/3/5_201/_article/-char/ja",
    "journal": "Journal of the Society for Remediation of Radioactive Contamination in the Environment",
    "category": "学際科学"
  },
  {
    "title": "界面合成法で作成した高耐アルカリ性フェロシアン化ニッケルの生成、分解およびセシウム吸着機構",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/3/5_215/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "哲学・宗教"
  },
  {
    "title": "除染等業務従事者等被ばく線量登録管理制度の運用について",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/3/5_227/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "文学・言語学・芸術学"
  },
  {
    "title": "福島県内の空間線量率トレンドの解析—環境半減期、積雪の影響—",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/2/5_79/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "人類学・史学・地理学"
  },
  {
    "title": "森林の土壌性状が放射性セシウムの地下浸透に及ぼす影響に関する分析",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/2/5_95/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "法学・政治学"
  },
  {
    "title": "除染特別地域における除染の実態と今後の課題 －2013年から2016年までの市町村アンケート調査の結果に基づいて－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/2/5_109/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "経済学・経営学"
  },
  {
    "title": "表面線量率及び表面汚染密度の測定による放射性セシウムの表面残存状況の評価",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/1/5_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "社会学"
  },
  {
    "title": "ポルトランドセメントにおけるセシウムの吸着状態の解析と汚染コンクリート廃材の減容化手法への応用",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/1/5_17/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "心理学・教育学"
  },
  {
    "title": "宮城県南部の小学校の除染4年後の除染効果",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/1/5_27/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "数学"
  },
  {
    "title": "多量の放射能汚染土壌（路面清掃土砂）の分級洗浄処理",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/1/5_35/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "物理学"
  },
  {
    "title": "除去土壌等減容化・再生利用技術研究組合の取り組みについて",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/5/1/5_47/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "化学"
  },
  {
    "title": "「匿名年金情報」に基づく国民年金保険料の納付状況に関する分析",
    "url": "https://www.jstage.jst.go.jp/article/nenkinkenkyu/30/0/30_1/_article/-char/ja",
    "journal": "年金研究",
    "category": "地球科学・天文学"
  },
  {
    "title": "加熱化学処理法による土壌・粘土鉱物からのセシウム揮発除去と揮発メカニズムの推定",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/4/4_303/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "生物学・生命科学・基礎医学"
  },
  {
    "title": "統計的手法及び深度分布調査による森林除染の効果に影響を及ぼす要因に関する分析",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/4/4_313/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "農学・食品科学"
  },
  {
    "title": "公衆被ばく線量限度とリスク等価な帰還時被ばく線量の推計",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/4/4_325/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般医学・社会医学・看護学"
  },
  {
    "title": "Csの物理的・化学的移行による土壌の減容化に関する研究",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/4/4_337/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "臨床医学"
  },
  {
    "title": "セルロース系バイオマスを利用した水熱処理によるバーミキュライトからのCs溶離技術に関する基礎研究",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_231/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "歯学"
  },
  {
    "title": "テトラフェニルホウ酸イオンによる水相セシウムの捕捉および有機イオン会合体相への濃縮",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_239/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "薬学"
  },
  {
    "title": "霞ヶ浦ワカサギ体内セシウムの経年変化",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_247/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "一般工学・総合工学"
  },
  {
    "title": "2015年に採取して干した野生キノコの放射性セシウム（Cs）の溶出速度",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_253/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "ナノ・材料科学"
  },
  {
    "title": "高線量域における除染について －双葉町・浪江町帰還困難区域モデル除染等工事－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_259/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "建築学・土木工学"
  },
  {
    "title": "茨城県取手市における放射能除染事業（住宅地・道路）",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/3/4_269/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "機械工学"
  },
  {
    "title": "被ばく線量評価に用いられる居住係数の再評価",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/2/4_97/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "電気電子工学"
  },
  {
    "title": "福島県における市町村主体の除染の実態と課題 －福島第一原子力発電所事故から4年半後の記録－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/2/4_105/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "情報科学"
  },
  {
    "title": "福島第一原子力発電所事故による放射能汚染水田土壌の除染効果の評価",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/2/4_141/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "環境学"
  },
  {
    "title": "光のアナロジーを活用した放射線理解促進ツールの開発",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/2/4_155/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "学際科学"
  },
  {
    "title": "乾式Cs除去技術の概要と飯舘村蕨平における仮設資材化実証調査委託業務について",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/2/4_165/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "哲学・宗教"
  },
  {
    "title": "水底放射能測定装置「みなそこ」による放射性物質現場測定手法の開発",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/1/4_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "文学・言語学・芸術学"
  },
  {
    "title": "除染特別地域における除染に関する市町村の評価・見解 －福島第一原子力発電所事故から4年半後の記録－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/1/4_15/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "人類学・史学・地理学"
  },
  {
    "title": "高効率・高減容セシウム回収システムの構築 －プルシアンブルー熱分解処理でのセシウム塩の挙動－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/1/4_35/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "法学・政治学"
  },
  {
    "title": "除去土壌等の減容化システムの構築への期待と課題 ～ 中間貯蔵から最終処分への技術的整合性を求めて～",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/1/4_47/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "経済学・経営学"
  },
  {
    "title": "分級による減容化～湿式分級とその課題～",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/4/1/4_61/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "社会学"
  },
  {
    "title": "除去土壌等の最終処分・再生利用に対する理解醸成等の取組み ― 若い世代向けの理解醸成 ―",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/13/4/13_113/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "心理学・教育学"
  },
  {
    "title": "カラム吸着による放射能汚染した飛灰洗浄液からのCs最大濃縮：吸着材評価の方法と影響因子",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/13/3/13_61/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "数学"
  },
  {
    "title": "除去土壌の再生利用と最終処分：社会受容への影響の比較",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/13/2/13_33/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "物理学"
  },
  {
    "title": "原発事故で長期避難指示を受けた地域の復興に対するステークホルダーの意識に関する研究 －福島県双葉町中間貯蔵施設立地地域を対象として－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/13/1/13_3/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "化学"
  },
  {
    "title": "帰還困難区域の復興・再生に向けた展開と到達点と課題 －特定帰還居住区域の指定実態を踏まえて－",
    "url": "https://www.jstage.jst.go.jp/article/jsrrce/12/4/12_111/_article/-char/ja",
    "journal": "環境放射能除染学会誌",
    "category": "地球科学・天文学"
  }
];
